# Generated by Django 4.2.23 on 2025-08-12 15:35

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influencer_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('second_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits.", regex='^\\+?1?\\d{7,15}$')])),
                ('country', models.CharField(blank=True, max_length=100)),
                ('social_tiktok', models.URLField(blank=True, max_length=500)),
                ('social_instagram', models.URLField(blank=True, max_length=500)),
                ('social_threads', models.URLField(blank=True, max_length=500)),
                ('social_x', models.URLField(blank=True, max_length=500)),
                ('social_linkedin', models.URLField(blank=True, max_length=500)),
                ('interests', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('description', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='influencers/profile_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Influencer',
                'verbose_name_plural': 'Influencers',
                'ordering': ['-created_at'],
            },
        ),
    ]
